---
title: "2021 AGSA R Workshop - Session 2 Agenda"
output: html_document
---

# 1) Setup  
```{r Setup, warning=F}
# Loading packages (everytime you open R)
library(dplyr) # wrangling
library(tidyr) # wrangling
library(purrr) # for iteration
library(ggplot2) # plotting
library(readr) # to read and write data
library(car) # Anova
library(broom.mixed) # model diagnostics
library(ggthemes) # ggplot customization

```


```{r soyk_w - Reading data}
soyk_w <- read_csv("../../data/SoybeanWorkshopProcessed.csv")

# Checking first rows
soyk_w

```

# 2) Exploratory Plots 
```{r Point and curve}
ggplot(soyk_w, aes(x=k_rate_kgha, y=k_pct))+
  geom_point(aes(color=location))+
  geom_smooth(method="lm")+
  facet_grid(.~location)

```

# 3) Regression for one Location  
```{r soyk_w2 - Wrangling a bit more}
# Creating rep and locatiom as categorical (factor)
soyk_w2 <- soyk_w %>%
  mutate(frep=factor(rep),
         flocation=factor(location)) 

soyk_w2
```

```{r Extracting only one location}
# Extracting only one location (s1)
soyk_w2_s1 <- soyk_w2 %>%
  filter(flocation=="s1")

soyk_w2_s1

```

```{r RCBD model for location s1}
options(contrasts = c("contr.sum", "contr.poly"))

soyk_reg_s1 <- lm(k_pct ~ frep +
                    k_rate_kgha,
                  data=soyk_w2_s1)

```

```{r tidy }
tidy(soyk_reg_s1)
```

```{r Anova}
Anova(soyk_reg_s1, type = 3)
```

# 4) Model Assumptions  
Why is this important?  

```{r Extracting residuals information}
soyk_reg_aug_s1 <- augment(soyk_reg_s1)

soyk_reg_aug_s1
```


## 4.1) Residuals are iid ~ N(0, var2)  

On this plot, looking for:  
- Spread around zero  
- Homogeneity (no patterns)  
- Outliers (>3 or <-3)  

```{r Standardized Residuals vs. Fitted, message=F, warning=F}
ggplot(soyk_reg_aug_s1, aes(x=.fitted, y=.std.resid))+
  geom_point(aes(color=frep))+
  geom_hline(yintercept = c(-3,0,3), color="orange")+
  geom_smooth()

```

On this plot, looking for normality (points on top of line)
```{r Quantile-Quantile}
ggplot(soyk_reg_aug_s1, aes(sample = .std.resid))+
  stat_qq()+
  stat_qq_line()
```

# 5) Automating analysis for all Locations with group_by(), nest(), and map()  
```{r Automated regression for all locations }

soyk_reg_all <- soyk_w2 %>%
  group_by(flocation) %>%
  nest() %>%
  # Fitting RCBD model
  mutate(mod = map(data,
                   ~lm(k_pct ~ frep + k_rate_kgha,
                       data = .x)
  )) %>%
  # Augmenting (for diagnostics and predictions)
  mutate(aug=map(mod,
                 ~augment(.x)
  )) %>%
  # Checking residuals 
  mutate(diag1=map2(aug, flocation,
                    ~ggplot(data=.x, aes(x=.fitted, y=.std.resid))+
                      geom_point(aes(color=frep))+
                      geom_hline(yintercept = c(-3,0,3), 
                                 color = "orange")+
                      geom_smooth()+
                      labs(title = paste0(.y))
  )) %>%
  # Anova 
  mutate(Anova = map(mod,
                     ~Anova(.x, type = 3)
  )) %>%
  # Extracting model coefficients for plotting
  mutate(tidy=map(mod,
                  ~tidy(.x) %>%
                    dplyr::select(term, estimate) %>%
                    pivot_wider(names_from = term,
                                values_from = estimate) %>%
                    rename(intercept=`(Intercept)`)
  )) %>%
  # Creating model formula to display on plot
  mutate(form=map(tidy,
                  ~.x %>% 
                    mutate(intercept=round(intercept,2),
                           k_rate_kgha=round(k_rate_kgha,5)
                           ) %>%
                    mutate(form=paste0("y = ",intercept," + ",k_rate_kgha)) %>%
                    dplyr::select(form)
                    ))

```

```{r Checking ANOVAs}
soyk_reg_all$Anova
```

```{r Checking Residuals, message=F, warning=F}
soyk_reg_all$diag1
```

# 6) Plotting it all  
```{r Plotting all with regression lines}
soyk_reg_all %>%
  unnest(aug) %>%
  ggplot(aes(x = k_rate_kgha, y = k_pct, 
             color = flocation, 
             group=flocation))+
  geom_point(aes(shape = flocation), 
             size = 2, 
             alpha = .6)+
  facet_wrap(.~flocation)+
  geom_abline(data=soyk_reg_all %>%
                unnest(tidy),
              aes(intercept=intercept,
                  slope=k_rate_kgha,
                  color=flocation))+
  geom_label(data=soyk_reg_all %>%
               unnest(form),
             aes(label=form, x=40, y=2)
             )+
  labs(x = "K Rate (kg K2O/ha)", 
       y = "Plant K (%)")+
  theme_solarized_2()+
  scale_color_tableau()+
  theme(legend.position = "none")

ggsave(filename = "../../output/Regression.png", 
       width = 8, 
       height = 6)
```

